name: Update News and Deploy

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape-and-build:
    if: "!contains(github.event.head_commit.message, 'chore: update news data')"
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'asd' || null }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Scraper
        run: npm run scrape
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_TOKEN }}

      - name: Build
        run: npm run build

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/data/news.json src/data/skipped.json
          git commit -m "chore: update news data [skip ci]" || echo "No changes to commit"
          git push origin ${{ github.ref_name }}

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: scrape-and-build
    if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
